import type { Metadata } from "next";
import { Cormorant_Garamond, Montserrat } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import Header from "./components/headers/Header";
import Footer from "./components/footers/Footer";
import Loader from "./components/loaders/Loader";
import CartBar from "./components/cart/CartBar";

// Headings — elegant, editorial serif that matches the nimi logo.
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// Body / UI — clean sans-serif for navigation, buttons, product info.
const montserrat = Montserrat({
  variable: "--font-body",
  subsets: ["latin"],
});

// Absolute base for Open Graph image URLs, so shared product links (e.g. in
// an Instagram DM) show a preview. Set NEXT_PUBLIC_SITE_URL in production.
const siteUrl =
  "https://thenimijewels.com/";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "nimi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${cormorantGaramond.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-body">
        <Loader />
        <Header />
        {children}
        <Footer />
        <CartBar />
      </body>
      {/* Google Analytics 4 (gtag.js) — loads after hydration. */}
      <GoogleAnalytics gaId="G-M6F1CPBSBW" />
    </html>
  );
}
